### PR TITLE
Pin docker image to 1.4 and readme update

### PR DESCRIPTION
**Pull request by divyansh42**
Signed-off-by: divyansh42 <diagrawa@redhat.com>

### Checklist

- [x] This PR includes a documentation change
- [ ] This PR does not need a documentation change
---
- [ ] This PR includes test changes
- [x] This PR's changes are already tested
---
- [ ] This change is not user-facing
- [ ] This change is a patch change
- [ ] This change is a minor change
- [ ] This change is a major (breaking) change

### CODE REVIEW

**Review by jduimovich — CHANGES_REQUESTED** [review]
The code changes LGTM.
I would like a few updates to the README to make things more clear. Specifically now that we're pinning to a specific version of the chart verifier we need to have a mapping so that when a user wants a specific chart verifier they can find the supported version that is pinned to it
1.0.0 maps -> chart verifier 1.4 
1.2 maps -> chart verifier 1.X ?
1.3 -> ?

We may want the action itself to simply match the version of the the verifier so you don't need to guess or look up in a table 
i.e 
our action 1.4 -> 1.4

Not sure how the chart verifier will bump versions but hopefully this could work. 

I would change the read me to 
- make it clear that each action version maps to a single chart verifier version
- what the mapping is (or naming convention) if we match version to version
- best practices (which you have) on how to use this.

In the future discussion we should discuss the workflow with the verifier team (i'll create an issue) so that a user could test the current "know working" verifier, and the "new one" to see if they pass the updated version as a dry run.

**Comment by divyansh42** [comment]
> We may want the action itself to simply match the version of the the verifier so you don't need to guess or look up in a table
i.e
our action 1.4 -> 1.4

This is indeed a great suggestion, we can probably confirm this with the chart-verifier team. If that works, this is the best option I think.

**Review by rtaniwa — APPROVED** [review]
Agree with @jduimovich changes. We would also need the readme to be updated to reflect the new versioning approach.

**Comment by divyansh42** [comment]
No more relevant.
We have PR #5

**Pull request closed without merging**
